language: android
android:
  components:
  - build-tools-28.0.3
  - android-28
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
licenses:
- android-sdk-preview-license-52d11cd2
- android-sdk-license-.+
- google-gdk-license-.+
script:
- jdk_switcher use openjdk8
- "./gradlew clean :library:build :library:testDebugUnitTestCoverage"
notifications:
  slack:
    secure: MWnm/nvl8UgUCGMjQDjHdAa7QDuSZgWJrd9SAJbfCjeo62L4TQ9tQ/vRmkEpI54+Q/3egjhiLjjHiqbFYufhPvuzFoN6TcvZyf0d1X9rjYxrzKnXOGJyDbvTRHVsvSW3A17p322VKFHiVfYiW+uKexdLRPSqJxXIrCiJMuRgk+lPxtqj31PTxHByBfixC9qLP/wThMDmQDDkU5tqwsDwkWz+lhNkgGOKRaT3JXxABygQSd9faBDzBYag8PXjUVZgrD5nYhjWTKs7750tBTbuCpP3NiWfEJOHzrugIJWUO73NjewgzMBaeva93yT3F4vReaL2hNxR9LONKm4GzvDXwgjU/b1whKKmJxo+tlZhLunAZBKxigD/OdoWb5yqVvU5VKemL4qtdFtdOdeYg5vdUv34rrRRVuf4vR9iI4/l1vN0GgDNGYszWKsdAThhCxmKFa/fB6sxnhqeYjAfOLrRPpaR28DrtbEVFF/f1SmwgYCYDLWuuE31f++k4odV2xgNrpu7NGdkZU5xPU9edwmXveoy81JGHGEkptdiTf7iK4SQ6FlVJppKZ1z8AbLDM24TUmYmZe9Gvy00v3gnLKSgSE/tgfrrEzfTdz1szbYYOFWHFvIpL6J2E44Dsq8QleloCpuOQLTFWPxWzpg40G5zYaJxlGNUoeN6LQqrKYl1d9k=
